### ISSUE TITLE
Confirm the order

### ISSUE THREAD

**Issue by DininduSenanayake** [GenomicsAotearoa/Pangenome-Graphs-Workshop#1]
@ZoeYang2020 @nuzla We have published the first iteration of the repo https://genomicsaotearoa.github.io/Pangenome-Graphs-Workshop/

Can you check whether the order on TOC table is correct ?. If not, please do post the correct order here and I will update the pages and TOC

**Comment by ZoeYang2020** [comment]
Hi Dini, 
Concerning the sequence and content on my part, the ideal order should be:
An introduction (currently titled as 'introduction 2'),
The construction of a pangenome graph using PGGB,
The analysis of NGS data using the graph as a reference.
And there is overlapping material between my content and Nuzla's. We should review this and decide what to retain during our in-person meeting next week.  
Thanks Zoe

**Comment by DininduSenanayake** [comment]
Thanks @ZoeYang2020. Perhaps the best approach is for @nuzla  and you to number the files in https://github.com/GenomicsAotearoa/Pangenome-Graphs-Workshop/tree/main/docs to reflect the order (except for the index.md file)  ?  . i.e. User the same format I have used for `1_intro.md` and `2_intro.md` as in `number_filename.md`

**Comment by DininduSenanayake** [comment]
Marking this as solved as the latest set of commits have addressed this  :)
