### ISSUE TITLE
BUS error ?

### ISSUE THREAD

**Issue by DininduSenanayake** [GenomicsAotearoa/Pangenome-Graphs-Workshop#2]
@JSBoey Can you confirm which `singularity` block triggered the `BUS error` which led the Jupyter session to crash ?

**Comment by JSBoey** [comment]
@DininduSenanayake It was the one linked [here](https://github.com/GenomicsAotearoa/Pangenome-Graphs-Workshop/blob/main/docs/1_Intro_1.md#3-executing-pggb-tool-using-singularity-container) that points [here](https://github.com/pangenome/pggb#singularity). The `singularity pull` produced the error.

**Comment by DininduSenanayake** [comment]
Thanks @JSBoey . Right, given the step immediately after that is to run a slurm job for this, I don't see the reason for running it interactively anyway. I believe that was written to describe the steps involved in executing the application,we can it down to a demo block and remove the bash header,etc.

**Comment by JSBoey** [comment]
I agree, there are a few code blocks like that which are amenable to be demo blocks (e.g. [here](https://genomicsaotearoa.github.io/Pangenome-Graphs-Workshop/pangenome_graph_construction/#odgi-paths-to-extract-distance)). I'll close this thread and open a new issue to make sure I tick the demo blocks off as I go.
