### ISSUE TITLE
PGGB does not complete

### ISSUE THREAD

**Issue by JSBoey** [GenomicsAotearoa/Pangenome-Graphs-Workshop#8]
PGGB exits are `smoothxg` with a non-zero status and does not continue to other modules.

```bash
module load pggb/0.5.3-Miniconda3

pggb -i 4Sim.fa -s 1000 -p 96 -n 4 -t 4 -S -m -o 4Sim_1K96 -V 'NC_017518:#'
```

Output:
```
Flag could not be matched: 'S'
  smoothxg {OPTIONS}
  ...

Command exited with non-zero status 1
smoothxg -t 4 -T 4 -g 4Sim_1K96/4Sim.fa.97e7156.417fcdf.seqwish.gfa -r 4 --base 4Sim_1K96 --chop-to 100 -I .9600 -R 0 -j 0 -e 0 -l 700,900,1100 -P 1,19,39,3,81,1 -O 0.001 -Y 400 -d 0 -D 0 -S -Q Consensus_ -V -o 4Sim_1K96/4Sim.fa.97e7156.417fcdf.7659dc8.smooth.gfa
0.00s user 0.00s system 66% cpu 0.01s total 9540Kb max memory
```

**Comment by JSBoey** [comment]
Execution of PGGB using Singularity container instead of `module load` runs to completion with required outputs. Cross-ref #5

**Comment by DininduSenanayake** [comment]
@JSBoey There is a hiddden `pggb` module built with the same Singularity image. Any chance you can try the run with that module and confirm the status ?

```
$ module load pggb/.0.5.3-singularity

$ pggb --help
ERROR: mandatory arguments -i and -n
ERROR: -n must be greater than or equal to 2
usage: /usr/local/bin/pggb -i <input-fasta> -n <n-haplotypes> [options]
options:
   [wfmash]
    -i, --input-fasta FILE      input FASTA/FASTQ file
    -s, --segment-length N      segment length for mapping [default: 5000]
    -l, --block-length N        min..
````

**Comment by DininduSenanayake** [comment]
@JSBoey This is because of the existing issue on pgge conda https://github.com/pangenome/pggb/issues/294. 

I have downgraded `smoothxg` version now to match the version in upstream container image. Can you try again and with `pggb/0.5.3-Miniconda3` module and confirm the status ?

**Comment by JSBoey** [comment]
@DininduSenanayake It is now running as expected. Thank you! I'll close this issue.
